name: Hold Docs Pr
on:
  # TODO: should this be `pull_request_target` for security?
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  # TODO: this could target files instead of watching for a label.
  pull_request:
    types: [labeled]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # need to check out code to be able to use `gh` CLI (needs a .git directory to get remote)
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/github-script@v6
        with:
          script: |
            const MERGE_LABEL = 'pr: automerge'
            const HOLD_LABEL = 'pr: hold'
            const DOCS_LABEL = 'pr: docs'

            const owner = context.payload.repository.owner;
            const ownerName = owner.login;
            const repo = context.payload.repository.name;

            if (context.payload.label.name === DOCS_LABEL) {
              const pr = context.payload.pull_request;
              const labelNames = pr.labels.map(l => l.name)
              console.log(`PR #${pr.number}: Docs PR found. Adding hold labels to prevent merge`);

              console.log('Labels', labelNames)

              // remove if exists
              if (labelNames.includes(MERGE_LABEL)) {
                console.log('removing automerge label')
                // https://octokit.github.io/rest.js/v18#issues-remove-label
                const res = await github.rest.issues.removeLabel({
                  issue_number: pr.number,
                  owner: ownerName,
                  repo: repo,
                  name: MERGE_LABEL
                })
                console.log(res);
              } else {
                console.log(`"${MERGE_LABEL}" label already removed`)
              }

              console.log('------------------------');

              if (labelNames.includes(HOLD_LABEL)) {
                console.log(`"${HOLD_LABEL}" label already exists`)
              } else {
                console.log(`Adding "${HOLD_LABEL}" label`)
                // https://octokit.github.io/rest.js/v18#issues-add-labels
                const res = await github.rest.issues.addLabels({
                  issue_number: pr.number,
                  owner: ownerName,
                  repo: repo,
                  labels: [HOLD_LABEL]
                });
                console.log(res);
              }
            } else {
              console.log(`${context.payload.label.name} label was applied, skipping this event`)
            }
