name: Merge Docs PR

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_run:
    workflows: [Release]

    # TODO: do we need to check if upstream workflow compleeted successfully?
    types: [completed]

jobs:
  DoIt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Labels
        shell: bash
        # TODO: the --label filter should only be for the release type from the upstream workflow...
        run: |
          ls -al
          gh pr list --label "pr: docs" --draft=false --json "number" | jq -c ".[]" | jq .number | xargs gh pr edit --remove-label="pr: hold" --add-label="pr: automerge"
