name: Merge Docs PR
on:
  workflow_run:
    workflows: [Release]

    # TODO: do we need to check if upstream workflow compleeted successfully?
    types: [completed]

jobs:
  DoIt:
    runs-on: ubuntu-latest
    steps:
      - run: "echo merged"
      # TODO: the --label filter should only be for the release type from the upstream workflow...
      - run: |
        gh pr list --label "pr: docs" --draft=false --json "number" | jq -c ".[]" | jq .number | xargs gh pr edit --remove-label="pr: hold" --add-label="pr: automerge"
