name: Merge Docs PR

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_run:
    workflows: [Release]

    # TODO: do we need to check if upstream workflow compleeted successfully?
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # need to check out code to be able to use `gh` CLI (needs a .git directory to get remote)
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug
        uses: actions/github-script@v6
        with:
          script: |
            const MERGE_LABEL = 'pr: automerge'
            const HOLD_LABEL = 'pr: hold'
            const DOCS_LABEL = 'pr: docs'

            console.log(context)
            console.log('------------------')
            console.log(context.workflow_run.actor)
            console.log('------------------')
            console.log(context.workflow_run.triggering_actor)
            console.log('------------------')
            console.log(github.event)

      - name: Update Labels
        shell: bash
        # TODO: the --label filter should only be for the release type from the upstream workflow...
        run: |
          DOCS_LABEL="\"pr: docs\""
          HOLD_LABEL="\"pr: hold\""
          AUTO_MERGE_LABEL="\"pr: automerge\""

          PR_NUMBERS=$(gh pr list --label "$DOCS_LABEL" --draft=false --json "number" | jq -c ".[]" | jq .number)

          for number in $PR_NUMBERS; do
            echo "PR#$number: Add labels: $AUTO_MERGE_LABEL, Remove labels: $HOLD_LABEL "
            gh pr edit "$number" --remove-label="$HOLD_LABEL" --add-label="$AUTO_MERGE_LABEL"
          done
