name: Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'SemVer Increment'
        required: true
        default: 'prerelease'
        type: choice
        options:
        - prerelease
        - prepatch
        - preminor
        - premajor
        - patch
        - minor
        - major
      identifier:
        description: 'npm Tag'
        required: true
        default: 'canary'
        type: choice
        options:
        - canary
        - latest
jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: "echo success"

